context:
  version: 5.4.0

package:
  name: bash-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/bash-language-server/-/bash-language-server-${{ version }}.tgz
  sha256: 398971fee90b72014d72ca63b163e8f19d3c7db9528de8e43075c2ffa579b7b2

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - bash-language-server --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language Server for Bash
  homepage: https://github.com/bash-lsp/bash-language-server
  repository: https://github.com/bash-lsp/bash-language-server

extra:
  recipe-maintainers:
    - danielnachun
